#!/usr/bin/env bash
# Revo CLI - context command
# Scans all cloned repos and writes a workspace-level CLAUDE.md.

# Topological sort over YAML_REPO_DEPS.
# Sets CONTEXT_ORDER to newline-separated repo indices (roots first).
# Sets CONTEXT_CYCLE=1 if a cycle was detected (remaining nodes are appended in input order).
CONTEXT_ORDER=""
CONTEXT_CYCLE=0

_context_topo_sort() {
    CONTEXT_ORDER=""
    CONTEXT_CYCLE=0

    local n="$YAML_REPO_COUNT"
    [[ $n -eq 0 ]] && return 0

    # placed[i]=1 once emitted
    local placed=()
    local i
    for ((i = 0; i < n; i++)); do
        placed[$i]=0
    done

    local remaining=$n
    local order=""

    # Repeat: find a node whose deps are all placed (or missing)
    while [[ $remaining -gt 0 ]]; do
        local made_progress=0
        for ((i = 0; i < n; i++)); do
            [[ ${placed[$i]} -eq 1 ]] && continue

            local deps="${YAML_REPO_DEPS[$i]:-}"
            local all_ready=1

            if [[ -n "$deps" ]]; then
                # Iterate over comma-separated dep names
                local dep
                local old_ifs="$IFS"
                IFS=','
                for dep in $deps; do
                    [[ -z "$dep" ]] && continue
                    local dep_idx
                    dep_idx=$(yaml_find_by_name "$dep")
                    # If the dep isn't in our config, ignore it
                    if [[ "$dep_idx" -lt 0 ]]; then
                        continue
                    fi
                    if [[ ${placed[$dep_idx]} -eq 0 ]]; then
                        all_ready=0
                        break
                    fi
                done
                IFS="$old_ifs"
            fi

            if [[ $all_ready -eq 1 ]]; then
                if [[ -z "$order" ]]; then
                    order="$i"
                else
                    order="$order"$'\n'"$i"
                fi
                placed[$i]=1
                remaining=$((remaining - 1))
                made_progress=1
            fi
        done

        if [[ $made_progress -eq 0 ]]; then
            # Cycle or unresolvable: append remaining in input order and stop
            CONTEXT_CYCLE=1
            for ((i = 0; i < n; i++)); do
                if [[ ${placed[$i]} -eq 0 ]]; then
                    if [[ -z "$order" ]]; then
                        order="$i"
                    else
                        order="$order"$'\n'"$i"
                    fi
                    placed[$i]=1
                fi
            done
            remaining=0
        fi
    done

    CONTEXT_ORDER="$order"
    return 0
}

# Markers used to delimit revo's auto-generated block inside the workspace
# CLAUDE.md. Anything between these markers is owned by `revo context` and
# replaced on every regeneration. Anything outside is preserved untouched.
CONTEXT_BEGIN_MARKER='<!-- BEGIN revo:auto - regenerated by `revo context`, do not edit between markers -->'
CONTEXT_END_MARKER='<!-- END revo:auto -->'

# Splice an auto-generated block into the target CLAUDE.md without
# clobbering user content.
#  - If target doesn't exist: copy auto file to target.
#  - If target has BEGIN+END markers: replace the marker block in place.
#  - Otherwise: append the auto block (with a separator) at the end.
# Usage: _context_merge_into "/tmp/auto" "/path/to/CLAUDE.md"
_context_merge_into() {
    local auto_file="$1"
    local target="$2"

    if [[ ! -f "$target" ]]; then
        cp "$auto_file" "$target"
        return 0
    fi

    if grep -qF "$CONTEXT_BEGIN_MARKER" "$target" 2>/dev/null \
        && grep -qF "$CONTEXT_END_MARKER" "$target" 2>/dev/null; then
        local merged
        merged=$(mktemp -t revo-merge.XXXXXX)
        awk -v auto="$auto_file" -v begin="$CONTEXT_BEGIN_MARKER" -v end="$CONTEXT_END_MARKER" '
            BEGIN { in_block = 0 }
            index($0, begin) == 1 {
                in_block = 1
                while ((getline line < auto) > 0) print line
                close(auto)
                next
            }
            index($0, end) == 1 && in_block {
                in_block = 0
                next
            }
            !in_block { print }
        ' "$target" > "$merged"
        mv "$merged" "$target"
        return 0
    fi

    # No markers — append at the end with a blank-line separator. If the
    # existing file doesn't end in a newline, add one first so we don't merge
    # into the user's last line.
    if [[ -s "$target" ]] && [[ -n "$(tail -c1 "$target" 2>/dev/null)" ]]; then
        printf '\n' >> "$target"
    fi
    printf '\n' >> "$target"
    cat "$auto_file" >> "$target"
    return 0
}

# Write the workspace CLAUDE.md to the given path. The auto-generated content
# is wrapped in BEGIN/END markers and spliced into any existing CLAUDE.md so
# user content above and below the markers is preserved across regenerations.
# Usage: _context_write_file "/path/to/CLAUDE.md"
_context_write_file() {
    local target="$1"
    local workspace
    workspace=$(config_workspace_name)

    local output
    output=$(mktemp -t revo-auto.XXXXXX)

    # Start auto block (markers + header)
    {
        printf '%s\n' "$CONTEXT_BEGIN_MARKER"
        printf '# Workspace Context (auto-generated by revo)\n'
        printf '\n'
        printf 'This workspace contains multiple repositories managed by revo.\n'
        if [[ -n "$workspace" ]]; then
            printf 'Workspace: **%s**\n' "$workspace"
        fi
        printf '\n'
        printf '> This block is auto-generated by `revo context`. Edits between the\n'
        printf '> BEGIN/END markers will be lost on regeneration. Add your own content\n'
        printf '> above or below the markers.\n'
        printf '\n'
        printf '## Repos\n'
        printf '\n'
    } > "$output"

    # Per-repo details
    local i
    for ((i = 0; i < YAML_REPO_COUNT; i++)); do
        local path tags deps url full_path
        path=$(yaml_get_path "$i")
        tags=$(yaml_get_tags "$i")
        deps=$(yaml_get_deps "$i")
        url=$(yaml_get_url "$i")
        full_path="$REVO_REPOS_DIR/$path"

        local branch
        branch=$(yaml_get_branch "$i")

        # Backfill: detect default branch for cloned repos that don't have one stored
        if [[ -z "$branch" ]] && [[ -d "$full_path" ]]; then
            branch=$(git_default_branch "$full_path")
            if [[ -n "$branch" ]]; then
                YAML_REPO_BRANCHES[$i]="$branch"
            fi
        fi

        {
            printf '### %s\n' "$path"

            if [[ -n "$tags" ]]; then
                printf -- '- **Tags:** %s\n' "$tags"
            fi
            printf -- '- **Path:** repos/%s\n' "$path"
            if [[ -n "$branch" ]] && [[ "$branch" != "$YAML_DEFAULTS_BRANCH" ]]; then
                printf -- '- **Default branch:** %s\n' "$branch"
            fi
            if [[ -n "$deps" ]]; then
                printf -- '- **Depends on:** %s\n' "$deps"
            fi
        } >> "$output"

        if [[ -d "$full_path" ]]; then
            scan_repo "$full_path"

            if [[ -n "$SCAN_LANG" ]]; then
                if [[ -n "$SCAN_NAME" ]]; then
                    printf -- '- **Package:** %s (%s)\n' "$SCAN_NAME" "$SCAN_LANG" >> "$output"
                else
                    printf -- '- **Language:** %s\n' "$SCAN_LANG" >> "$output"
                fi
            fi

            if [[ -n "$SCAN_FRAMEWORK" ]]; then
                printf -- '- **Framework:** %s\n' "$SCAN_FRAMEWORK" >> "$output"
            fi

            if [[ -n "$SCAN_ROUTES" ]]; then
                printf -- '- **API routes:** %s\n' "$SCAN_ROUTES" >> "$output"
            fi

            if [[ -n "$SCAN_DESCRIPTION" ]]; then
                printf -- '- **Description:** %s\n' "$SCAN_DESCRIPTION" >> "$output"
            fi

            if [[ $SCAN_HAS_CLAUDE_MD -eq 1 ]]; then
                printf -- '- **Has CLAUDE.md:** yes (repo-level context available)\n' >> "$output"
            fi

            if [[ $SCAN_HAS_DOCKER -eq 1 ]]; then
                printf -- '- **Containerized:** yes\n' >> "$output"
            fi

            local db_type db_name
            db_type=$(yaml_get_db_type "$i")
            db_name=$(yaml_get_db_name "$i")
            if [[ -n "$db_type" ]] && [[ -n "$db_name" ]]; then
                if [[ -n "${REVO_ACTIVE_WORKSPACE:-}" ]]; then
                    local ws_db
                    ws_db=$(_db_workspace_name "$db_name" "$REVO_ACTIVE_WORKSPACE")
                    printf -- '- **Database (workspace):** %s (%s)\n' "$ws_db" "$db_type" >> "$output"
                else
                    printf -- '- **Database:** %s (%s)\n' "$db_name" "$db_type" >> "$output"
                fi
            fi
        else
            printf -- '- **Status:** not cloned (run `revo clone`)\n' >> "$output"
            if [[ -n "$url" ]]; then
                printf -- '- **URL:** %s\n' "$url" >> "$output"
            fi
        fi

        printf '\n' >> "$output"
    done

    # Dependency order
    {
        printf '## Dependency Order\n'
        printf '\n'
        printf 'When making cross-repo changes, follow this order:\n'
        printf '\n'
    } >> "$output"

    _context_topo_sort

    local step=1
    local idx
    while IFS= read -r idx; do
        [[ -z "$idx" ]] && continue
        local path deps
        path=$(yaml_get_path "$idx")
        deps=$(yaml_get_deps "$idx")
        if [[ -n "$deps" ]]; then
            printf '%d. **%s** (after: %s)\n' "$step" "$path" "$deps" >> "$output"
        else
            printf '%d. **%s**\n' "$step" "$path" >> "$output"
        fi
        step=$((step + 1))
    done <<< "$CONTEXT_ORDER"

    if [[ $CONTEXT_CYCLE -eq 1 ]]; then
        printf '\n> Warning: a dependency cycle was detected. Listed in best-effort order.\n' >> "$output"
    fi

    # Active workspaces (any .revo/workspaces/*/ dirs)
    local workspaces_dir="$REVO_WORKSPACE_ROOT/.revo/workspaces"
    if [[ -d "$workspaces_dir" ]]; then
        local has_workspaces=0
        local ws
        for ws in "$workspaces_dir"/*/; do
            [[ -d "$ws" ]] || continue
            if [[ $has_workspaces -eq 0 ]]; then
                {
                    printf '\n'
                    printf '## Active Workspaces\n'
                    printf '\n'
                } >> "$output"
                has_workspaces=1
            fi
            local ws_name
            ws_name=$(basename "$ws")
            printf -- '- **%s** — `.revo/workspaces/%s/` (branch: feature/%s)\n' \
                "$ws_name" "$ws_name" "$ws_name" >> "$output"
        done
        if [[ $has_workspaces -eq 1 ]]; then
            {
                printf '\n'
                printf 'Run `revo workspaces` for branch/dirty status, or `cd` into one\n'
                printf 'and run revo from there to operate on the workspace copy.\n'
            } >> "$output"
        fi
    fi

    # Active features (any .revo/features/*.md files)
    local features_dir="$REVO_WORKSPACE_ROOT/.revo/features"
    if [[ -d "$features_dir" ]]; then
        local has_features=0
        local f
        for f in "$features_dir"/*.md; do
            [[ -f "$f" ]] || continue
            if [[ $has_features -eq 0 ]]; then
                {
                    printf '\n'
                    printf '## Active Features\n'
                    printf '\n'
                } >> "$output"
                has_features=1
            fi
            local fname rel
            fname=$(basename "$f" .md)
            rel=".revo/features/$(basename "$f")"
            printf -- '- **%s** — see [%s](%s)\n' "$fname" "$rel" "$rel" >> "$output"
        done
    fi

    # Agent instructions — directive workflows for Claude Code
    {
        printf '\n'
        printf '## Agent Instructions\n'
        printf '\n'
        printf 'You are working in a multi-repo workspace managed by **revo**. Do NOT explore\n'
        printf 'to figure out what revo is — it is a CLI tool already installed in the terminal. Use it.\n'
        printf '\n'
        printf '### Critical Rules\n'
        printf '\n'
        printf -- '- ALWAYS read `.revo/features/<name>.md` before starting work on any feature. It contains the plan.\n'
        printf -- '- NEVER ask "what is the scope?" for a feature that has a feature file. The file IS the scope.\n'
        printf -- '- When uncertain about revo commands, run `revo --help` or read `.revo/COMMANDS.md`.\n'
        printf -- '- Use `revo` commands for all cross-repo git operations. Do not manually cd into each repo and run git.\n'
        printf -- '- Each repo may have its own CLAUDE.md with repo-specific instructions — read it when working in that repo.\n'
        printf -- '- Follow the dependency order above when making cross-repo changes.\n'
        printf '\n'
        printf '### Workflows\n'
        printf '\n'
        printf '**"Work on feature X" or "Begin work on X":**\n'
        printf '1. Read `.revo/features/X.md` for the plan (if it does not exist, run `revo feature X` first)\n'
        printf '2. Run `revo status` to confirm you are on the right branches\n'
        printf '3. Start implementing according to the plan. Follow the dependency order in this file.\n'
        printf '\n'
        printf '**"Work on feature X use workspaces" or "use workspace":**\n'
        printf '1. Run `revo workspace X` to create an isolated copy at `.revo/workspaces/X/`\n'
        printf '2. cd into `.revo/workspaces/X/` — all subsequent revo commands operate on the workspace\n'
        printf '3. Read `.revo/features/X.md` (in the workspace root) for context\n'
        printf '4. Implement the feature. Commit with `revo commit "msg"` when ready.\n'
        printf '\n'
        printf '**"Create a feature for X" or "Plan feature X":**\n'
        printf '1. Run `revo feature X` to create branches and `.revo/features/X.md`\n'
        printf '2. Edit `.revo/features/X.md` with the plan (scope, affected repos, approach)\n'
        printf '\n'
        printf '**"Commit" or "Save progress":**\n'
        printf '1. Run `revo commit "descriptive message"` — stages and commits all dirty repos\n'
        printf '\n'
        printf '**"Push and PR" or "Open pull requests":**\n'
        printf '1. Run `revo push` to push all branches\n'
        printf '2. Run `revo pr "PR title"` to create coordinated, cross-referenced PRs\n'
        printf '\n'
        printf '**"Status" or "Sync":**\n'
        printf '1. `revo status` — branch and dirty state across all repos\n'
        printf '2. `revo sync` — pull latest across all repos\n'
        printf '\n'
        printf '### Quick Reference\n'
        printf '\n'
        printf 'Run `revo --help` for all commands. Key ones: `status`, `commit`, `push`,\n'
        printf '`pr`, `feature`, `workspace`, `sync`, `exec`, `checkout default`, `issue list`.\n'
        printf 'All commands accept `--tag TAG` to filter by repo tag.\n'
        printf 'See `.revo/COMMANDS.md` for the full command reference with examples.\n'
        printf '\n'
        printf '%s\n' "$CONTEXT_END_MARKER"
    } >> "$output"

    # Splice the auto block into the target file, preserving any user content.
    _context_merge_into "$output" "$target"
    rm -f "$output"
}

# Write the .revo/COMMANDS.md reference file. Detailed command docs that
# Claude Code can read on-demand, kept out of the main CLAUDE.md so the
# agent sees directive workflows first, not a wall of syntax.
_context_write_commands_file() {
    local target="$REVO_WORKSPACE_ROOT/.revo/COMMANDS.md"
    mkdir -p "$REVO_WORKSPACE_ROOT/.revo"

    {
        printf '# revo Command Reference\n'
        printf '\n'
        printf 'Source: https://github.com/jippylong12/revo\n'
        printf '\n'
        printf '## Setup\n'
        printf '\n'
        printf -- '- `revo add <git-url> --tags <tags> [--depends-on <repo>]` — add a repo\n'
        printf -- '- `revo clone` — clone all configured repos\n'
        printf -- '- `revo context` — regenerate workspace CLAUDE.md\n'
        printf -- '- `revo detect` — bootstrap around existing repos in cwd\n'
        printf '\n'
        printf '## Daily Workflow\n'
        printf '\n'
        printf -- '- `revo status` — branch and dirty state across all repos\n'
        printf -- '- `revo sync` — pull latest across all repos\n'
        printf -- '- `revo feature <name> [--tag t]` — create feature branch across repos\n'
        printf -- '- `revo commit "msg" [--tag t]` — commit all dirty repos\n'
        printf -- '- `revo push [--tag t]` — push all repos\n'
        printf -- '- `revo pr "title" [--tag t]` — create coordinated PRs via gh CLI\n'
        printf -- '- `revo exec "cmd" [--tag t]` — run command in filtered repos\n'
        printf -- '- `revo checkout <branch> [--tag t]` — switch branch across repos\n'
        printf -- '- `revo checkout default` — switch each repo to its own default branch (handles mixed main/master)\n'
        printf '\n'
        printf '## Workspaces\n'
        printf '\n'
        printf -- '- `revo workspace <name> [--tag t]` — full copy of repos into `.revo/workspaces/<name>/` on `feature/<name>`\n'
        printf -- '- `revo workspaces` — list active workspaces with branch and dirty state\n'
        printf -- '- `revo workspace <name> --delete [--force]` — remove a workspace\n'
        printf -- '- `revo workspace --clean` — remove workspaces whose branches are merged\n'
        printf '\n'
        printf 'Workspaces hardlink-copy everything (including `.env`, `node_modules`,\n'
        printf 'build artifacts) so you can start work with zero bootstrap. Run\n'
        printf '`revo` from inside `.revo/workspaces/<name>/` and it operates on the\n'
        printf 'workspace copies, not the source tree.\n'
        printf '\n'
        printf '## Issues (cross-repo, via gh CLI)\n'
        printf '\n'
        printf -- '- `revo issue list [--tag t] [--state open|closed|all] [--label L] [--json]` — list issues across repos\n'
        printf -- '- `revo issue create --repo <name> "title" [--body b] [--label L] [--feature F]` — create in one repo\n'
        printf -- '- `revo issue create --tag <t> "title" [--body b] [--feature F]` — create in every matching repo, cross-referenced\n'
        printf '\n'
        printf 'Use `--json` on `revo issue list` to get a flat JSON array (each entry has\n'
        printf 'a `repo` field) — easy to filter or pipe into jq.\n'
        printf '\n'
        printf '## Tag Filtering\n'
        printf '\n'
        printf 'All commands support `--tag <tag>` to target specific repos:\n'
        printf '\n'
        printf '```\n'
        printf 'revo exec "npm test" --tag frontend\n'
        printf 'revo sync --tag backend\n'
        printf 'revo commit "fix: typo" --tag api\n'
        printf '```\n'
        printf '\n'
        printf '## Feature Workflow\n'
        printf '\n'
        printf '```\n'
        printf 'revo feature my-feature          # branches all repos, writes .revo/features/my-feature.md\n'
        printf '# edit .revo/features/my-feature.md with your plan\n'
        printf '# work across repos\n'
        printf 'revo commit "feat: my feature"   # commits all dirty repos\n'
        printf 'revo push                        # push all branches\n'
        printf 'revo pr "My feature"             # coordinated PRs\n'
        printf '```\n'
        printf '\n'
        printf '## Workspace Workflow\n'
        printf '\n'
        printf '```\n'
        printf 'revo workspace my-feature        # full copy to .revo/workspaces/my-feature/\n'
        printf 'cd .revo/workspaces/my-feature   # enter the workspace\n'
        printf 'revo status                      # operates on workspace repos\n'
        printf '# work across repos\n'
        printf 'revo commit "feat: my feature"   # commits workspace repos\n'
        printf 'revo push                        # push workspace branches\n'
        printf 'revo pr "My feature"             # coordinated PRs from workspace\n'
        printf 'cd ../../..                      # back to main workspace\n'
        printf 'revo workspace my-feature --delete  # clean up\n'
        printf '```\n'
    } > "$target"
}

cmd_context() {
    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --help|-h)
                printf 'Usage: revo context\n\n'
                printf 'Scan repos and regenerate workspace CLAUDE.md with framework,\n'
                printf 'routes, and dependency order for Claude Code to consume.\n'
                return 0
                ;;
            *)
                ui_step_error "Unknown option: $1"
                return 1
                ;;
        esac
    done

    config_require_workspace || return 1

    ui_intro "Revo - Generate Workspace CLAUDE.md"

    if [[ $YAML_REPO_COUNT -eq 0 ]]; then
        ui_step_error "No repositories configured"
        ui_outro_cancel "Nothing to scan"
        return 1
    fi

    local output="$REVO_WORKSPACE_ROOT/CLAUDE.md"

    ui_spinner_start "Scanning $YAML_REPO_COUNT repositories..."
    _context_write_file "$output"
    # Persist any newly detected per-repo branches back to revo.yaml
    config_save
    ui_spinner_stop
    _context_write_commands_file
    ui_step_done "Scanned:" "$YAML_REPO_COUNT repositories"
    ui_step_done "Wrote:" "CLAUDE.md"
    ui_step_done "Wrote:" ".revo/COMMANDS.md"

    if [[ $CONTEXT_CYCLE -eq 1 ]]; then
        ui_step_error "Dependency cycle detected - see CLAUDE.md for order"
    fi

    ui_outro "Context generated. Point Claude Code at this workspace."

    return 0
}

# Called automatically from cmd_clone after a successful clone batch.
# Always rewrites the workspace CLAUDE.md so newly cloned repos show up.
context_regenerate_silent() {
    [[ -z "$REVO_WORKSPACE_ROOT" ]] && return 0
    [[ $YAML_REPO_COUNT -eq 0 ]] && return 0

    local output="$REVO_WORKSPACE_ROOT/CLAUDE.md"
    _context_write_file "$output"
    _context_write_commands_file
    ui_info "$(ui_dim "Regenerated CLAUDE.md for Claude Code")"
    return 0
}
