#!/usr/bin/env bash
# Revo CLI - context command
# Scans all cloned repos and writes a workspace-level CLAUDE.md.

# Topological sort over YAML_REPO_DEPS.
# Sets CONTEXT_ORDER to newline-separated repo indices (roots first).
# Sets CONTEXT_CYCLE=1 if a cycle was detected (remaining nodes are appended in input order).
CONTEXT_ORDER=""
CONTEXT_CYCLE=0

_context_topo_sort() {
    CONTEXT_ORDER=""
    CONTEXT_CYCLE=0

    local n="$YAML_REPO_COUNT"
    [[ $n -eq 0 ]] && return 0

    # placed[i]=1 once emitted
    local placed=()
    local i
    for ((i = 0; i < n; i++)); do
        placed[$i]=0
    done

    local remaining=$n
    local order=""

    # Repeat: find a node whose deps are all placed (or missing)
    while [[ $remaining -gt 0 ]]; do
        local made_progress=0
        for ((i = 0; i < n; i++)); do
            [[ ${placed[$i]} -eq 1 ]] && continue

            local deps="${YAML_REPO_DEPS[$i]:-}"
            local all_ready=1

            if [[ -n "$deps" ]]; then
                # Iterate over comma-separated dep names
                local dep
                local old_ifs="$IFS"
                IFS=','
                for dep in $deps; do
                    [[ -z "$dep" ]] && continue
                    local dep_idx
                    dep_idx=$(yaml_find_by_name "$dep")
                    # If the dep isn't in our config, ignore it
                    if [[ "$dep_idx" -lt 0 ]]; then
                        continue
                    fi
                    if [[ ${placed[$dep_idx]} -eq 0 ]]; then
                        all_ready=0
                        break
                    fi
                done
                IFS="$old_ifs"
            fi

            if [[ $all_ready -eq 1 ]]; then
                if [[ -z "$order" ]]; then
                    order="$i"
                else
                    order="$order"$'\n'"$i"
                fi
                placed[$i]=1
                remaining=$((remaining - 1))
                made_progress=1
            fi
        done

        if [[ $made_progress -eq 0 ]]; then
            # Cycle or unresolvable: append remaining in input order and stop
            CONTEXT_CYCLE=1
            for ((i = 0; i < n; i++)); do
                if [[ ${placed[$i]} -eq 0 ]]; then
                    if [[ -z "$order" ]]; then
                        order="$i"
                    else
                        order="$order"$'\n'"$i"
                    fi
                    placed[$i]=1
                fi
            done
            remaining=0
        fi
    done

    CONTEXT_ORDER="$order"
    return 0
}

# Write the workspace CLAUDE.md to the given path.
# Usage: _context_write_file "/path/to/CLAUDE.md"
_context_write_file() {
    local output="$1"
    local workspace
    workspace=$(config_workspace_name)

    # Start file
    {
        printf '# Workspace Context (auto-generated by revo)\n'
        printf '\n'
        printf 'This workspace contains multiple repositories managed by revo.\n'
        if [[ -n "$workspace" ]]; then
            printf 'Workspace: **%s**\n' "$workspace"
        fi
        printf '\n'
        printf '> This file is regenerated by `revo context`. Manual edits below the\n'
        printf '> `## Agent Instructions` section will be preserved across regeneration.\n'
        printf '\n'
        printf '## Repos\n'
        printf '\n'
    } > "$output"

    # Per-repo details
    local i
    for ((i = 0; i < YAML_REPO_COUNT; i++)); do
        local path tags deps url full_path
        path=$(yaml_get_path "$i")
        tags=$(yaml_get_tags "$i")
        deps=$(yaml_get_deps "$i")
        url=$(yaml_get_url "$i")
        full_path="$REVO_REPOS_DIR/$path"

        {
            printf '### %s\n' "$path"

            if [[ -n "$tags" ]]; then
                printf -- '- **Tags:** %s\n' "$tags"
            fi
            printf -- '- **Path:** repos/%s\n' "$path"
            if [[ -n "$deps" ]]; then
                printf -- '- **Depends on:** %s\n' "$deps"
            fi
        } >> "$output"

        if [[ -d "$full_path" ]]; then
            scan_repo "$full_path"

            if [[ -n "$SCAN_LANG" ]]; then
                if [[ -n "$SCAN_NAME" ]]; then
                    printf -- '- **Package:** %s (%s)\n' "$SCAN_NAME" "$SCAN_LANG" >> "$output"
                else
                    printf -- '- **Language:** %s\n' "$SCAN_LANG" >> "$output"
                fi
            fi

            if [[ -n "$SCAN_FRAMEWORK" ]]; then
                printf -- '- **Framework:** %s\n' "$SCAN_FRAMEWORK" >> "$output"
            fi

            if [[ -n "$SCAN_ROUTES" ]]; then
                printf -- '- **API routes:** %s\n' "$SCAN_ROUTES" >> "$output"
            fi

            if [[ -n "$SCAN_DESCRIPTION" ]]; then
                printf -- '- **Description:** %s\n' "$SCAN_DESCRIPTION" >> "$output"
            fi

            if [[ $SCAN_HAS_CLAUDE_MD -eq 1 ]]; then
                printf -- '- **Has CLAUDE.md:** yes (repo-level context available)\n' >> "$output"
            fi

            if [[ $SCAN_HAS_DOCKER -eq 1 ]]; then
                printf -- '- **Containerized:** yes\n' >> "$output"
            fi
        else
            printf -- '- **Status:** not cloned (run `revo clone`)\n' >> "$output"
            if [[ -n "$url" ]]; then
                printf -- '- **URL:** %s\n' "$url" >> "$output"
            fi
        fi

        printf '\n' >> "$output"
    done

    # Dependency order
    {
        printf '## Dependency Order\n'
        printf '\n'
        printf 'When making cross-repo changes, follow this order:\n'
        printf '\n'
    } >> "$output"

    _context_topo_sort

    local step=1
    local idx
    while IFS= read -r idx; do
        [[ -z "$idx" ]] && continue
        local path deps
        path=$(yaml_get_path "$idx")
        deps=$(yaml_get_deps "$idx")
        if [[ -n "$deps" ]]; then
            printf '%d. **%s** (after: %s)\n' "$step" "$path" "$deps" >> "$output"
        else
            printf '%d. **%s**\n' "$step" "$path" >> "$output"
        fi
        step=$((step + 1))
    done <<< "$CONTEXT_ORDER"

    if [[ $CONTEXT_CYCLE -eq 1 ]]; then
        printf '\n> Warning: a dependency cycle was detected. Listed in best-effort order.\n' >> "$output"
    fi

    # Agent instructions
    {
        printf '\n'
        printf '## Agent Instructions\n'
        printf '\n'
        printf 'When working in this workspace:\n'
        printf '\n'
        printf '1. Read this file first to understand the repo structure\n'
        printf '2. Check `.revo/features/` for active feature contexts\n'
        printf '3. Follow the dependency order above when making cross-repo changes\n'
        printf '4. Each repo may have its own CLAUDE.md with repo-specific instructions\n'
        printf '5. Use `revo status` to check state across all repos\n'
        printf '6. Use `revo commit "msg"` to commit across all repos at once\n'
        printf '7. Use `revo feature <name>` to start a coordinated feature workspace\n'
        printf '8. Use `revo pr "title"` to open coordinated pull requests\n'
    } >> "$output"
}

cmd_context() {
    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --help|-h)
                printf 'Usage: revo context\n\n'
                printf 'Scan repos and regenerate workspace CLAUDE.md with framework,\n'
                printf 'routes, and dependency order for Claude Code to consume.\n'
                return 0
                ;;
            *)
                ui_step_error "Unknown option: $1"
                return 1
                ;;
        esac
    done

    config_require_workspace || return 1

    ui_intro "Revo - Generate Workspace CLAUDE.md"

    if [[ $YAML_REPO_COUNT -eq 0 ]]; then
        ui_step_error "No repositories configured"
        ui_outro_cancel "Nothing to scan"
        return 1
    fi

    local output="$REVO_WORKSPACE_ROOT/CLAUDE.md"

    ui_spinner_start "Scanning $YAML_REPO_COUNT repositories..."
    _context_write_file "$output"
    ui_spinner_stop
    ui_step_done "Scanned:" "$YAML_REPO_COUNT repositories"
    ui_step_done "Wrote:" "CLAUDE.md"

    if [[ $CONTEXT_CYCLE -eq 1 ]]; then
        ui_step_error "Dependency cycle detected - see CLAUDE.md for order"
    fi

    ui_outro "Context generated. Point Claude Code at this workspace."

    return 0
}

# Called automatically from cmd_clone if CLAUDE.md does not yet exist.
context_autogenerate_if_missing() {
    [[ -z "$REVO_WORKSPACE_ROOT" ]] && return 0
    local output="$REVO_WORKSPACE_ROOT/CLAUDE.md"
    [[ -f "$output" ]] && return 0
    [[ $YAML_REPO_COUNT -eq 0 ]] && return 0

    _context_write_file "$output"
    ui_info "$(ui_dim "Auto-generated CLAUDE.md for Claude Code")"
    return 0
}
